inherit_from:
  - .rubocop_airbnb.yml
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - db/schema.rb
    - 'db/migrate/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'lib/tasks/*'
    - db/seeds.rb

Metrics/LineLength:
  Max: 115
