inherit_from:
  - .rubocop_airbnb.yml

AllCops:
  Exclude:
    - db/schema.rb
    - 'db/migrate/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'lib/tasks/*'
    - db/seeds.rb
    - vendor/**/*

Metrics/LineLength:
  Enabled: false

Style/BlockComments:
  Enabled: false

Airbnb/OptArgParameters:
  Enabled: false
